include:
#  - board: nice_nano_v2
#    shield: cosmos_left
    
  - board: nice_nano_v2
    shield: cosmos_right
    
  - board: nice_nano_v2
    shield: cosmos_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    # snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: settings_reset