# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  - board: nice_nano_v2
#    shield: thumbsupv5
#  - board: nice_nano_v2
#    shield: thumbsupv9 
  - board: nice_nano_v2
    shield: a_ball_dongle
#    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
 # Add these cmake-args to the peripherals you wish to use with the dongle
  - board: nice_nano_v2
    shield: a_ball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n