manifest:
  remotes:
    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
      url-base: https://github.com/trentrand
    - name: badjeff
#      url-base: https://github.com/badjeff
      url-base: https://github.com/trentrand
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
#    - name: zmk-pmw3610-driver
    - name: zmk-pmw3360-driver
      remote: badjeff
      revision: main
  self:
    path: config

