file_format: "1"
id: a_ball_d
name: a_ball_d
type: shield
url: https://github.com/ak66666/ThumbsUp-Trackball
requires: [pro_micro]
features:
  - pointer
  - dongle
siblings:
  - a_ball_d_r
  - a_ball_d_d
